title: Polygon
remote_theme: b2a3e8/jekyll-theme-console
header_pages:
  - index.md

style: dark # dark (default), light or hacker
listen_for_clients_preferred_style: true # false (default) or true

<<<<<<< HEAD
footer: 'follow me on <a href="https://twitter.com/PolygonTransit">twitter</a>'
=======
footer: '© 2022 Polygon Transit'

>>>>>>> parent of bb0c0a9 (Complete overhaul of site)
google_analytics: G-B0LL0TDDCB
