title: Polygon
author: Polygon Transit
description: "Fonts and things."
url: "https://polygontransit.github.io"
remote_theme: b2a3e8/jekyll-theme-console
header_pages:
  - index.md
  - fonts.md
  - links.md
  - videos.md
  - _posts

style: dark # dark (default), light or hacker
listen_for_clients_preferred_style: true # false (default) or true

footer: 'follow me on <a href="https://twitter.com/PolygonTransit">twitter</a>'

google_analytics: G-TBHR7QE4NL