title: Polygon
description: "Fonts and things."
-url: "https://polygontransit.github.io"
remote_theme: b2a3e8/jekyll-theme-console
header_pages:
  - index.md
  - fonts.md
  - links.md

style: dark # dark (default), light or hacker
listen_for_clients_preferred_style: true # false (default) or true

footer: '© 2022 Polygon Transit'

google_analytics: G-B0LL0TDDCB
